slashid/javascript

packages/react/src/components/form/form.tsx, packages/react/src/components/form/index.tsx, packages/react/src/components/icon/index.ts, packages/react/src/context/config-context.tsx, packages/react/src/theme/theme.css.ts
Enable the customers to specify the theme behaviour - `light | dark | auto`.
=> [SID-659] Implement the theme prop

apps/kyc-demo/package.json, apps/react-nextjs/package.json, apps/react-remix/package.json, apps/react-vite/package.json, packages/demo-form/package.json, packages/react/package.json, pnpm-lock.yaml
[YouTrack issue](https://todo.irdcorp.dev/issue/SID-768)
Update the core SDK reference.
=> [SID-768] Update the core SDK

apps/react-remix/app/slash-id.tsx, apps/react-remix/remix.config.js
Minor Remix app align with the docs update.
=> Adjust Remix app

.github/workflows/ci.yml, dangerfile.js, package.json, pnpm-lock.yaml
[YouTrack issue](https://todo.irdcorp.dev/issue/SID-331)
We want to have an informative bundle changes message.
=> [SID-331] Add bundle size check

.changeset/witty-terms-fetch.md, packages/react/package.json, packages/react/src/components/form/initial.tsx, packages/react/src/context/slash-id-context.tsx, pnpm-lock.yaml
[YouTrack issue](https://todo.irdcorp.dev/issue/SID-920)
Expose the analytics config options from the core SDK.
=> [SID-920] Expose client side analytics config

.changeset/polite-donkeys-speak.md, packages/react/src/components/form/initial.tsx, packages/react/src/dev.tsx
[YouTrack issue](https://todo.irdcorp.dev/issue/SID-1015)
The form would not update to dynamic updates of the passed configuration.
=> [SID-1015] Make sure the form reacts properly to dynamic configuration

.changeset/red-beers-refuse.md
Adding missing changeset from #89
=> [SID-1094] Changeset for SlashIDLoaded, isLoading, isAuthenticated

.changeset/silly-queens-grin.md, packages/react/src/main.ts
[YouTrack issue](https://todo.irdcorp.dev/issue/SID-1165)
This is a temporarily solution as a result of shelving https://github.com/slashid/javascript/pull/121.
=> [SID-1165] Move middleware to root

.changeset/new-carpets-brake.md, packages/react/package.json, packages/react/src/components/form/initial/handle-form.tsx, packages/react/src/components/text/constants.ts, pnpm-lock.yaml
[YouTrack issue](https://todo.irdcorp.dev/issue/SID-1198)
=> Bump Core SDK dependency 3.12.0 -> 3.13.0

packages/react/package.json, pnpm-lock.yaml
Fixing a typo which CI didn't catch
=> fix mistaken dependency

apps/react-nextjs/pages/gdpr-consent-dialog.tsx, apps/react-nextjs/pages/index.tsx, apps/react-remix/app/routes/index.tsx, packages/demo-form/src/index.ts, packages/demo-form/src/pages/FormPage/index.tsx, packages/demo-form/src/pages/GDPRConsentDialogPage/gdpr-consent-dialog-page.tsx, packages/demo-form/src/pages/GDPRConsentDialogPage/index.tsx, packages/demo-form/src/pages/MFAPage/index.tsx, packages/demo-form/src/pages/StepUpAuthPage/index.tsx
Added GDPR Consent Dialog demo to `react-nextjs` and `react-remix` apps to test SSR behavior.
=> Add GDPR Consent Dialog demo

packages/demo-form/src/pages/FormPage/form-page.tsx
[YouTrack issue](https://todo.irdcorp.dev/issue/SID-1263)
Changing link to reference doc to reflect new doc structure
=> [SID-1263] fix broken reference doc link

.changeset/olive-onions-prove.md, packages/react/src/components/form/authenticating.tsx, packages/react/src/components/text/constants.ts, packages/react/src/domain/handles.ts, packages/react/src/domain/types.ts
=> Improve the OTP flow states

.changeset/angry-boxes-fly.md, packages/react/src/components/dropdown/index.tsx
=> Add Dropdown Item docs

packages/react/src/components/form/form.test.tsx, packages/react/src/components/test-utils.ts, packages/react/src/context/test-slash-id-provider.tsx
[YouTrack issue](https://todo.irdcorp.dev/issue/SID-1323)
Following the fix for last handle, we want to extend the tests to cover the blind spots.
=> [SID-1323] Add last handle write test

.changeset/two-donuts-matter.md
=> Prepare for release - SAML

.changeset/grumpy-cows-applaud.md, packages/react/.gitignore, packages/react/package.json, packages/react/scripts/test-setup.js, packages/react/src/components/form/form.test.tsx, packages/react/src/components/test-utils.ts, packages/react/src/context/slash-id-context.tsx, packages/react/src/hooks/use-last-handle.ts, pnpm-lock.yaml
Dependencies:
- https://github.com/slashid/ng-evangelion/pull/1200
- https://github.com/slashid/ng-evangelion/pull/1204
[YouTrack issue](https://todo.irdcorp.dev/issue/SID-1368)
- Any time the user is stored record this as a "person identified" (login, parse from token storage)
- When the user explicitly logs out, record this as a "person logged out"
- Make analytics on by default
=> [SID-1368] Record logout and person identified analytics events, make analytics opt-out

packages/react/src/components/test-utils.ts
=> Remove debug

packages/remix/README.md
Change to fix the banner on npm: https://www.npmjs.com/package/@slashid/remix
=> Remix: README - absolute banner URL

apps/slashid-remix-impl/package.json, pnpm-lock.yaml
=> Fix remix primitives impl app

.changeset/grumpy-seas-buy.md, packages/remix/README.md
This PR applies feedback from internal usability testing
=> Remix: improve quickstart

packages/remix/package.json, pnpm-lock.yaml
=> Update Core SDK for Remix SDK

packages/react/src/hooks/use-last-handle.ts
This is a companion to: https://github.com/slashid/javascript/pull/211
=> React: gracefully handle last handle setting for block-all-cookies

.changeset/shy-poems-shop.md, packages/react/package.json, packages/react/src/context/slash-id-context.tsx, packages/react/src/dev.tsx, packages/remix/package.json, pnpm-lock.yaml
[YouTrack issue](https://todo.irdcorp.dev/issue/SID-1542)
After MFA is performed, the user instance is mutated but it does not change identity, skipping the render cycle. In this PR I made sure a new instance is created instead, so the components can react to it as expected.
=> [SID-1542] React SDK: Trigger a render after performing MFA

.changeset/swift-cats-drive.md, packages/react/package.json, packages/react/src/components/dynamic-flow/handle-form.tsx, packages/react/src/components/dynamic-flow/initial.tsx, packages/react/src/components/dynamic-flow/oidc.css.ts, packages/react/src/components/dynamic-flow/oidc.tsx, packages/react/src/components/form/initial/controls.tsx, packages/react/src/components/form/initial/sso.tsx, packages/react/src/dev.tsx, pnpm-lock.yaml
[YouTrack issue](https://todo.irdcorp.dev/issue/SID-1609)
Added Apple as an OIDC provider
=> [SID-1609] Add Apple as an OIDC provider

.changeset/spotty-forks-sell.md, packages/react-primitives/src/components/icon/loading.css.ts, packages/react-primitives/src/components/spinner/circle.css.ts, packages/react-primitives/src/components/spinner/circle.tsx
[YouTrack issue](https://todo.irdcorp.dev/issue/SID-1622)
Make spinner use
=> React primitives: Use primary color for spinner

.changeset/kind-balloons-build.md
=> Add the changeset

.github/workflows/bundle-size.yml, .github/workflows/bundle.yml, .github/workflows/ci.yml, apps/slashid-remix-impl/app/routes/form.tsx, apps/slashid-remix-impl/app/slashid.ts, apps/slashid-remix-impl/package.json, packages/tests/e2e/auth.spec.ts, packages/tests/playwright.config.ts, pnpm-lock.yaml, turbo.json
[YouTrack issue](https://todo.irdcorp.dev/issue/SID-1651)
Added a trivial e2e test that checks if the Remix SDK can be used to build and run a remix app. Full flow tests that include page navigation will come next.
=> [SID-1651] Add the e2e smoke test for @slashid/react-remix

.changeset/poor-rockets-live.md
[YouTrack issue](https://todo.irdcorp.dev/issue/SID-1591)
Added the missing changeset.
=> [SID-1591] Anonymous users: Add the changeset

.changeset/famous-taxis-taste.md, .changeset/twenty-parrots-tie.md, packages/react/package.json, packages/react/src/components/form/authenticating/password.tsx, packages/react/src/components/form/error/error.css.ts, packages/react/src/components/form/error/error.test.tsx, packages/react/src/components/form/error/index.tsx, packages/react/src/components/form/flow.ts, packages/react/src/components/form/form.test.tsx, packages/react/src/components/test-utils.ts, packages/react/src/components/text/constants.ts, packages/react/src/context/config-context.tsx, packages/react/src/dev.tsx, packages/react/src/domain/errors.ts, packages/react/src/domain/types.ts, packages/react/src/utils/css-validation.ts, pnpm-lock.yaml
[YouTrack issue](https://todo.irdcorp.dev/issue/SID-1697)
The `Form` will render the error state if the user attempts account recovery using a non-reachable handle.
=> [SID-1697] Granular error states: using a non-reachable handle type to recover

.changeset/blue-cycles-tickle.md, packages/react/package.json, packages/react/src/components/form/flow.ts, packages/react/src/domain/errors.ts
[YouTrack issue](https://todo.irdcorp.dev/issue/SID-1742)
=> [SID-1742] Use the same flow cancellation mechanism for flow retries

.changeset/clean-fishes-fetch.md, packages/react/src/components/text/constants.ts
[YouTrack issue](https://todo.irdcorp.dev/issue/SID-1755)
This PR adjust the copy to make it more general and less confusing.
=> [SID-1755] React SDK: Authenticating state copy update

.changeset/spicy-starfishes-bake.md, packages/react/package.json, packages/react/src/components/form/error/index.tsx, packages/react/src/components/text/constants.ts, pnpm-lock.yaml
[YouTrack issue](https://todo.irdcorp.dev/issue/SID-1743)
Companion: https://github.com/slashid/ng-evangelion/pull/1945
- Add a corresponding error state in form for when the jump page displays a "magic link expired" error
=> [SID-1743] React: authentication expired error handling

.changeset/chilled-glasses-travel.md, .changeset/rich-plums-tap.md, packages/react/package.json, packages/remix/package.json, pnpm-lock.yaml
=> Upgrade to core SDK to improve handling of cancelled flows

.changeset/tame-rocks-tease.md, packages/react/package.json, packages/react/src/utils/customisation.ts
[YouTrack issue](https://todo.irdcorp.dev/issue/SID-1932)
This PR adds sanitizer for primary hover color. This changes is required to unblock both Console and Login Page.
=> [SID-1932] React SDK: Allow customization of primary hover color

.changeset/friendly-keys-fry.md, .changeset/rare-windows-develop.md, packages/react/package.json, packages/react/src/components/form/error/index.tsx, packages/react/src/components/text/constants.ts, packages/remix/package.json, pnpm-lock.yaml
[YouTrack issue](https://todo.irdcorp.dev/issue/SID-1704)
[YouTrack issue](https://todo.irdcorp.dev/issue/SID-1938)
Show a dedicated UI when the BE returns an error resulting from a malformed handle value.
=> [SID-1938, SID-1704] Error UIs for handle format errors

.changeset/ten-hairs-reply.md, packages/react/src/components/form/authenticating/authenticating.components.tsx, packages/react/src/components/form/authenticating/authenticating.css.ts
=> React SDK: Fix the retry prompt on mobile

.changeset/fast-seals-marry.md, packages/react-primitives/package.json, packages/react-primitives/src/components/card/card.component.tsx, packages/react-primitives/src/components/card/card.css.ts, packages/react-primitives/src/components/card/index.tsx, packages/react-primitives/src/components/input/index.tsx, packages/react-primitives/src/components/input/input.uncontrolled.tsx, packages/react-primitives/src/components/text/index.tsx, packages/react-primitives/src/main.ts, packages/react/package.json, packages/react/src/components/form/form.tsx, packages/react/src/components/form/states.tsx, packages/react/src/components/onboarding/index.tsx, packages/react/src/components/onboarding/onboarding-actions.component.tsx, packages/react/src/components/onboarding/onboarding-context.hook.tsx, packages/react/src/components/onboarding/onboarding-form.component.tsx, packages/react/src/components/onboarding/onboarding-step.component.tsx, packages/react/src/components/onboarding/onboarding-success.component.tsx, packages/react/src/components/onboarding/onboarding.component.tsx, packages/react/src/components/onboarding/onboarding.css.ts, packages/react/src/components/onboarding/onboarding.test.tsx, packages/react/src/components/onboarding/onboarding.types.tsx, packages/react/src/components/text/constants.ts, packages/react/src/context/test-providers.tsx, packages/react/src/dev.tsx, packages/react/src/main.ts
[YouTrack issue](https://todo.irdcorp.dev/issue/SID-2004)
Onboarding API - tested in the login page project.
=> [SID-2004] Onboarding component

.changeset/sixty-cherries-do.md, packages/react/package.json, pnpm-lock.yaml
=> React SDK: Bump Radix select

.changeset/rare-pans-sneeze.md, packages/react-primitives/package.json, packages/react-primitives/src/components/dropdown/dropdown.css.ts, packages/react-primitives/src/components/dropdown/index.tsx, packages/react/package.json, packages/react/src/components/organization-switcher/index.tsx, pnpm-lock.yaml
=> React SDK: Fix Radix primitives

.changeset/serious-scissors-tie.md, package.json, packages/react/package.json, packages/react/src/components/form/org-switching/org-switching-form.test.tsx, packages/remix/package.json, pnpm-lock.yaml
=> Patch npm vulnerabilities
