slashid/javascript

.changeset/modern-dogs-swim.md, packages/react/src/components/form/form.css.ts
[YouTrack issue](https://todo.irdcorp.dev/issue/SID-679)
We want to set the `box-sizing: border-box` on the Form component to make it easier for users to set desired width for the whole form.
=> [SID-679] Adjust Form component box sizing

.changeset/silver-files-pretend.md, packages/react/src/components/form/flow.ts, packages/react/src/components/form/form.test.tsx, packages/react/src/components/form/form.tsx, packages/react/src/components/form/success.tsx, packages/react/src/components/form/useFlowState.ts
[YouTrack issue](https://todo.irdcorp.dev/issue/SID-680)
There is a common requirement for a callback prop fired when the authentication via `<Form />` component is successful
=> [SID-680] Form onSuccess props

.changeset/tidy-mangos-bake.md, packages/react/index.html, packages/react/package.json, packages/react/src/components/form/index.tsx, pnpm-lock.yaml
[YouTrack issue](https://todo.irdcorp.dev/issue/SID-850)
We want to exclude Inter font from our CSS bundle - with the font the file is ~4MiB, without ~22KiB
=> [SID-850] Exclude font from the bundle

.changeset/gold-berries-attack.md, packages/react/index.html, packages/react/src/theme/theme.css.ts
Add sans-serif as font fallback
=> Use sans-serif as default font

.changeset/eighty-vans-explode.md, packages/react/src/components/text/constants.ts
[YouTrack issue](https://todo.irdcorp.dev/issue/SID-967)
Most users will not know what Webauthn means, so using Passkeys will give a more friendly experience.
=> [SID-967] Change 'WebAuthn' wording to 'Passkeys'

.changeset/few-papayas-collect.md, packages/react/src/context/slash-id-context.tsx, packages/react/src/context/test-slash-id-provider.tsx, packages/react/src/hooks/use-slash-id.test.tsx
[YouTrack issue](https://todo.irdcorp.dev/issue/SID-948)
Allow passing in an external token to the SDK (some clients might store the token somewhere else).
=> [SID-948] Allow passing in an external token to the SDK

.changeset/tender-horses-wait.md, packages/react/package.json, packages/react/src/components/form/initial.tsx, packages/react/src/components/icon/azuread.tsx, pnpm-lock.yaml
[YouTrack issue](https://todo.irdcorp.dev/issue/SID-959)
Added the corresponding `azuread` icon when selecting it as the OIDC provider. Bumped up the core SDK dependency to match the generated client.
=> [SID-959] Add the Azure AD icon

.changeset/sour-gorillas-care.md, packages/react/src/components/loaded/index.tsx
I noticed when implementing `SlashIDLoaded` in `suborg-demo` that the prop types are clunky, I'm changing them.
=> fix: remove JSX.Element type from SlashIDLoaded props

.changeset/ninety-scissors-help.md, .changeset/tricky-toys-grow.md, packages/react/package.json, packages/react/src/dev.tsx, packages/react/src/domain/types.ts, packages/react/src/middleware/default-organization/default-organization.test.ts, packages/react/src/middleware/default-organization/index.ts, packages/react/src/middleware/index.ts
[YouTrack issue](https://todo.irdcorp.dev/issue/SID-1165)
1. The `LoginMiddleware` interface is referenced in the doc but is not clearly available.
2. `defaultOrganization` is not available from the middleware index file
=> [SID-1165] React SDK: improve middleware sub-package interface

.changeset/spotty-games-film.md, packages/react/package.json, packages/react/scripts/test-setup.js, packages/react/src/components/dynamic-flow/dynamic-flow.test.tsx, packages/react/src/components/form/form.test.tsx, packages/react/src/components/test-utils.ts, packages/react/src/context/slash-id-context.tsx, packages/react/src/mocks/handlers.ts, packages/react/src/mocks/server.ts, packages/react/src/tests/login-logout-flow.test.tsx, pnpm-lock.yaml
[YouTrack issue](https://todo.irdcorp.dev/issue/SID-1186)
We have a bug in the React SDK. Steps to reproduce:
- start anew, new tab, clean storage etc
- register with a new address
- create a suborg and switch to it
- logout without closing the tab
- you'll be presented with the form again, register with another new address
=> **the request to /id goes out with
- the token for the previously logged-in user
- the OrgID of the suborg, not the demo root**
After logging out, create a new SlashID instance with the root organization ID and no token.
=> [SID-1186] Reset the Org ID and SID instance on logout

.changeset/old-moose-hang.md, packages/react/package.json, packages/react/src/context/slash-id-context.tsx, pnpm-lock.yaml
[YouTrack issue](https://todo.irdcorp.dev/issue/SID-1190)
Fixes bug with org switching and stale SDK state after logout
=> [SID-1190] Upgrade to @slashid/slashid@3.13.2

.changeset/cyan-mangos-judge.md, packages/react/package.json, packages/react/src/components/dropdown/index.tsx, packages/react/src/components/organization-switcher/index.tsx, packages/react/src/components/organization-switcher/organization-switcher.stories.tsx, packages/react/src/components/organization-switcher/organization-switcher.test.tsx, packages/react/yalc.next.js, pnpm-lock.yaml
[YouTrack issue](https://todo.irdcorp.dev/issue/SID-1206)
Two changes
- Add `renderLabel` prop to `<OrganizationSwitcher>`, see context.
- I'm changing `Dropdown` to allow `ReactNode` for `label`
- The type is now `{ value: string, label: ReactNode }`
- Add npm script `next`. It automatically publishes things to `yalc` with a bumped pre-release version.
The org list currently renders org names "as is" which can create some interesting problems for consumers when weighing up the options for choosing a programmatically generated organization name scheme.
This change proposes allowing org name overrides (i.e. display names) in the most prominent place the org name is shown: the org switcher.
This feature gives flexibility to consumers to choose internal-only names for programmatically …
=> [SID-1206] Add renderLabel prop to <OrganizationSwitcher>

.github/workflows/release.yml, .github/workflows/unstable-release.yml
[YouTrack issue](https://todo.irdcorp.dev/issue/SID-1214)
We want a low friction way to test new sdk versions before they're public.
Each time a changeset is merged to main we should publish a snapshot with a invalid semver version behind the `@next` tag
Changeset `--snapshot` generates a version like this: `0.0.0-next-20230825102611`
=> [SID-1214] add unstable/nightly release

.changeset/pretty-chairs-help.md, packages/react/src/components/dialog/index.tsx, packages/react/src/components/gdpr-consent-dialog/consent-dialog.tsx, packages/react/src/components/gdpr-consent-dialog/gdpr-consent-dialog.test.tsx, packages/react/src/components/gdpr-consent-dialog/style.css.ts, packages/react/src/components/gdpr-consent-dialog/trigger-button.tsx, packages/react/src/components/gdpr-consent-dialog/types.ts, packages/react/src/components/teleport/index.tsx, packages/react/src/components/teleport/util.ts
[YouTrack issue](https://todo.irdcorp.dev/issue/SID-1196)
I encountered some issues trying to implement the component in my test bench.
1. Implementing the `container` prop is quite clunky, and the prop doesn't have parity with the `mui/modal` implementation which was the reference
2. Dismiss behaviour not as expected, dismiss by clicking background should only happen in modal mode
3. The advanced mode ("Customize") has truncated buttons because the element isn't wide enough
4. The cookie button does not appear in the portal, so it still suffers the same problem as the dialog did before
- `<Dialog />`
- Improve the `container` prop API, bringing it into parity with `mui/modal`
- The main improvement here is allowing an (internally cached) getter function for locating the original DOM …
=> [SID-1196] Improve GDPRConsentDialog usability

.github/workflows/unstable-release.yml
[YouTrack issue](https://todo.irdcorp.dev/issue/SID-1214)
Unstable publish [failed](https://github.com/slashid/javascript/actions/runs/6013643387/job/16311531987) because of missing npm token
=> [SID-1214] Generate npmrc before publish

packages/react/src/components/dropdown/dropdown.css.ts, packages/react/src/components/dropdown/index.tsx
[YouTrack issue](https://todo.irdcorp.dev/issue/SID-1231)
Very small CSS change - the spacing in this component between text and icon don't look very professional
Before:
After:
Before:
After:
=> [SID-1231] Improve dropdown spacing

.changeset/sweet-rice-call.md, packages/react/src/components/gdpr-consent-dialog/index.tsx, packages/react/src/hooks/use-gdpr-consent.test.tsx, packages/react/src/hooks/use-gdpr-consent.ts, packages/react/src/main.ts
[YouTrack issue](https://todo.irdcorp.dev/issue/SID-1233)
We expose the `useGdprConsent` hook without any inline docs - fixed with this PR.
=> [SID-1233] Add inline docs for the GDPR hook

.changeset/khaki-cups-deny.md, packages/react/src/components/gdpr-consent-dialog/consent-dialog.tsx, packages/react/src/components/gdpr-consent-dialog/gdpr-consent-dialog.test.tsx, packages/react/src/components/gdpr-consent-dialog/settings.tsx, packages/react/src/components/gdpr-consent-dialog/types.ts
[YouTrack issue](https://todo.irdcorp.dev/issue/SID-1239)
`necessaryCookiesRequired` should behave this way:
- when `true` it should render a lock instead of a toggle for the corresponding level and be accepted by default
- when `false` (default) the toggle for `necessary` should behave as any other toggle
=> [SID-1239] GDPR: when necessaryCookiesRequired is set to false, enable the toggle for that level

packages/react/src/components/dynamic-flow/initial.tsx, packages/react/src/components/form/authenticating.tsx, packages/react/src/components/form/error.tsx, packages/react/src/components/form/initial/index.tsx, packages/react/src/components/form/success.tsx
[Githubissue](https://github.com/slashid/javascript/issues/154)
Fix the color and font-weight in the `<Form>` component following Significa's last feedback:
1. [On the authenticating state and success/fail state of the signin/sign-up component, the fontweight of the title should be 700 (500 in the implementation).pdf](https://github.com/slashid/javascript/files/12600388/On.the.authenticating.state.and.success.fail.state.faf53b3c2dca41f0904b0175ad6622a8.pdf)
2. [On the sign-in/sign-up component, the color of the description should be “lightTheme/contrast” (in the implementation is “lightTheme/tertiary”).pdf](https://github.com/slashid/javascript/files/12600403/On.the.sign-in.sign-up.component.the.color.of.the.b7b6bbc318864a378e6efe9621918e61.pdf)
=> [Issue-154] Fix the color and font-weight in the <Form> component

.changeset/seven-tomatoes-hang.md, packages/react/package.json, pnpm-lock.yaml
Upgrading to set requirement for [@slashid/slashid@3.14.0](https://github.com/slashid/ng-evangelion/pull/1038)
=> React SDK: bump core sdk peer dep to 3.14.0

.changeset/pretty-lobsters-lick.md, packages/react/src/components/dialog/style.css.ts, packages/react/src/components/spinner/circle.css.ts
1. Fixed GDPR dialog close button outline.
2. Fixed Login form icon position.
=> Fix GDPR dialog close button outline and Login form icon position

.changeset/honest-vans-rescue.md, .changeset/ninety-boxes-rescue.md, packages/react/src/components/form/initial/initial.css.ts, packages/react/src/components/form/initial/logo.tsx, packages/react/src/components/spinner/circle.css.ts
[YouTrack issue 1](https://todo.irdcorp.dev/issue/SID-1360)
[YouTrack issue 2](https://todo.irdcorp.dev/issue/SID-1361)
Shopify uses a CSS reset that hides all empty divs and we use empty divs for loading and error icons. Added a rule to prevent that. 
Limited the height of the logo in the form to 32 pixels per design. Also the logo will now correctly use the SlashID logo if an empty string is provided in the configuration.
=> [SID-1361, SID-1360] Make sure the loading/error icons are displayed consistently, limit the logo height and use a safe default

.changeset/old-pens-shake.md, .changeset/silent-sloths-help.md, apps/jump-page/README.md, apps/jump-page/cli.js, apps/jump-page/package.json, apps/jump-page/src/components/app/app.component.tsx, apps/jump-page/src/config.ts, packages/react/package.json, pnpm-lock.yaml
[YouTrack issue](https://todo.irdcorp.dev/issue/SID-1424)
`@slashid/jump-page` will now expose a CLI used to start the dev server, parametrized via CLI options.
This will be used in order to run the jump page locally, from `task up`.
=> [SID-1424] Jump page: run the server via CLI

.changeset/ninety-adults-allow.md, packages/react-primitives/package.json, packages/react/package.json, packages/react/src/dev.tsx, pnpm-lock.yaml
Bump up the core SDK to 3.17.1
=> [SID-maintenance] Bump up the core SDK to 3.17.1

.changeset/few-students-hide.md, .changeset/hungry-experts-roll.md, .changeset/tidy-years-argue.md, packages/react-primitives/package.json, packages/react/package.json, packages/react/tsconfig.json, packages/react/tsconfig.node.json, packages/react/vite.config.ts, packages/react/vite.shared.ts, packages/react/vitest.config.ts, pnpm-lock.yaml
[YouTrack issue](https://todo.irdcorp.dev/issue/SID-1460)
Previously to this PR, `@slashid/react-primitives` was an internal package that had to be exposed via `npm` in order for anyone to install the `@slashid/react` package, given that even though it was internal we still had a reference to it in `package.json`.
With these changes, we remove the dependency and include an alias in order for `@slashid/react` to import the code outside of its relative project root. This way, there is no dependency so customers now only need to install the base package and `@slashid/react-primitives` does not need to be published.
=> [SID-1460] React SDK: do not expose the internal package

.changeset/loud-garlics-taste.md, dangerfile.js, packages/react/src/domain/types.ts, packages/react/src/hooks/use-last-handle.ts
[YouTrack issue](https://todo.irdcorp.dev/issue/SID-1464)
Fixes a bug with handle storage and direct-id, I'm adding `isHandle` type guard function which asserts the shape and content of things masquerading as a `Handle`.
Invalid handles should be discarded and not stored
If the `idFlowSucceeded` event fires and `handle` is `undefined`, `undefined` will be stored as the last handle. This causes things to break.
=> [SID-1464] Dont store bad handles with storeLastHandle

.changeset/unlucky-dolphins-teach.md, apps/slashid-remix-impl/package.json, apps/slashid-remix-impl/tsconfig.json, packages/remix/package.json, packages/remix/tsconfig.json, packages/remix/tsconfig.node.json, packages/remix/vite.config.js, pnpm-lock.yaml
Basically I fell into the `react-primitives` trap, and published a broken version.
It's fixed now and I'm correcting the record.
`@slashid/remix@0.1.1` is already published, I did it manually.
=> Remix: revert primitives trap

.changeset/fifty-houses-chew.md, packages/react/src/hooks/use-last-handle.ts
Users with "Block all cookies" enabled will see a crash when loading the form.
- Fail gracefully if accessing local storage fails when checking last handle
=> React: graceful fail for block-all-cookies

.changeset/khaki-forks-do.md, packages/react-primitives/src/components/tabs/index.tsx, packages/react/src/components/configuration-overrides/index.tsx, packages/react/src/components/dynamic-flow/configured-handle-form.tsx, packages/react/src/components/dynamic-flow/handle-form.tsx, packages/react/src/components/form/form-customisation.test.tsx, packages/react/src/components/form/form.test.tsx, packages/react/src/components/form/initial/controls.tsx, packages/react/src/components/test-utils.ts, packages/react/src/components/text/constants.ts, packages/react/src/dev.tsx, packages/react/src/domain/handles.ts, packages/react/src/domain/types.ts
[YouTrack issue](https://todo.irdcorp.dev/issue/SID-1546)
This change adds `allowedHandleTypes` to `password` factor method, as it's currently the only factor that supports both email and phone number handle types.
The motivation behind this change is: there are valid use cases where the user wants to explicitly declare the supported handle types. Good example is Shopify and SlashID Login app - Multipass works only with emails, so the phone number option should not be shown.
=> [SID-1546] Add possibility to specify allowed handle types for factors with multiple handle types

.changeset/tidy-icons-vanish.md, .changeset/wise-actors-taste.md, packages/react-primitives/src/components/delayed/index.tsx, packages/react-primitives/src/components/input/input.otp.css.ts, packages/react-primitives/src/main.ts, packages/react/src/components/form/authenticating/authenticating.css.ts, packages/react/src/components/form/authenticating/messages.ts, packages/react/src/components/form/authenticating/otp.tsx, packages/react/src/components/text/constants.ts
[YouTrack issue](https://todo.irdcorp.dev/issue/SID-1421)
[YouTrack issue](https://todo.irdcorp.dev/issue/SID-1529)
Changes:
- Create <Delayed> component in `react-primitives`
- Clear input and show error message when incorrect OTP code is submitted
- Transition to `retry` state on retry, add corresponding UI
Testing:
- Authenticate with OTP via email
- Enter incorrect code
- Input should be cleared and error message displayed
- Resend code
- You should see temporary retry UI
- Once you get the code, you should see the fresh empty input state
=> [SID-1421][SID-1529] Improve OTP error & resend handling

.changeset/hip-dancers-rule.md, apps/react-nextjs/pages/_app.tsx, apps/react-remix/app/slash-id.tsx, apps/react-vite/src/main.tsx, packages/react-primitives/.storybook/preview.tsx, packages/react/.storybook/preview.tsx, packages/react/src/context/slash-id-context.tsx, packages/react/src/dev.tsx, packages/react/src/hooks/use-slash-id.test.tsx
[YouTrack issue](https://todo.irdcorp.dev/issue/SID-1400)
The Core SDK have changed the environment config API some time ago, we want to update React SDK to enable the same configuration.
=> [SID-1400] Add `environment` prop to `<SlashIDProvider>`

.changeset/early-seals-yell.md, packages/react/src/components/form/initial/logo.tsx
Add a wrapper around the `<img>` element, allowing flexbox alignment without hurting the images natural size
There is a discrepancy between the markup for img vs /id (svg) logo:
```html
<div className="[logo-classes]">
<Logo>
</div>
```
vs
```html
```
In the case of `img`, it's not possible to use flex alignment CSS because there is no flex container around the logo itself.
=> React: add wrapper for image logo

.changeset/young-baboons-explode.md, dangerfile.js, packages/react/src/components/form/authenticating/icons.tsx
[YouTrack issue](https://todo.irdcorp.dev/issue/SID-1667)
So far the `<Form>` loading state did not adapt to the primary colour, which is expected based on other use cases. This is now fixed.
=> [SID-1667] Form loading state using the primary colour

.changeset/angry-beans-wave.md, packages/react/src/components/groups/groups.test.tsx, packages/react/src/components/groups/index.tsx, packages/react/src/components/logged-in/logged-in.test.tsx, packages/react/src/components/logged-out/logged-out.test.tsx, packages/react/src/context/slash-id-context.tsx, packages/react/src/context/test-providers.tsx, packages/react/src/domain/user.ts, packages/react/src/hooks/use-gdpr-consent.ts, packages/react/src/tests/anonymous-users.test.tsx
In this version of the anonymous users API, anon users are exposed through the additional `anonymous` user property of the `useSlashID` hook.
If we choose this solution, we also need to update the docs as the API is different.
=> [Anon fix] Extend the API with anon users instead of mutating it

.changeset/modern-bottles-return.md, packages/react/src/context/slash-id-context.tsx
[YouTrack issue](https://todo.irdcorp.dev/issue/SID-1669)
Up until now any time we stored the user in the React SDK context we also triggered the `person identified` event in the core SDK analytics. This resulted with duplicate events being fired, as the analytics internally already subscribed to the core SDK events so they were being tracked internally.
To fix this, only the function responsible for creating a user object from a stored token triggers this event from the React SDK - all other cases are covered in the core SDK.
=> [SID-1669] React SDK: fix person identified event being fired twice

.changeset/twenty-parrots-tie.md, packages/react/package.json, packages/react/src/components/form/authenticating/password.tsx, packages/react/src/components/form/error/error.test.tsx, packages/react/src/components/form/error/index.tsx, packages/react/src/components/form/form-error.test.tsx, packages/react/src/components/form/form.test.tsx, packages/react/src/components/test-utils.ts, packages/react/src/components/text/constants.ts, packages/react/src/context/config-context.tsx, packages/react/src/domain/errors.ts, packages/react/src/utils/css-validation.ts, pnpm-lock.yaml
[YouTrack issue](https://todo.irdcorp.dev/issue/SID-1699)
When a user that was created with username only (eg no reachable handles) tries to sign in with a password, they shouldn't be able to set a password in case they haven't had one to start with.
This throws a specific error type that the React SDK picks up and renders the error state of the form accordingly.
=> [SID-1699] Granular error states: user with a no password set + no reachable handle

.changeset/thick-walls-protect.md, packages/react-primitives/src/components/read-only-field/read-only-field.css.ts
Fixing a circular dependency in `react-primitives`
=> [Hotfix] Fix the circ dep in react-primitives

.changeset/dirty-vans-laugh.md, .changeset/good-spiders-wash.md, packages/react/src/components/form/authenticating/icons.tsx, packages/react/src/components/form/authenticating/index.tsx, packages/react/src/components/form/authenticating/messages.ts, packages/react/src/components/form/authenticating/otp.tsx, packages/react/src/components/form/error/error.test.tsx, packages/react/src/components/form/error/index.tsx, packages/react/src/components/form/form-customisation.test.tsx, packages/react/src/components/form/form.test.tsx, packages/react/src/components/text/constants.ts, packages/react/src/dev.tsx
[YouTrack issue](https://todo.irdcorp.dev/issue/SID-1561)
Sometimes people make typos when trying to sign up with SlashID. Once you submit the form, you can't see the exact handle you just typed in anymore. We want to add this information, so that people can see if they made a typo in case they don't receive an email or sms.
=> [SID-1561] Display handle value in authenticating state

.changeset/dull-baboons-search.md, .changeset/violet-goats-drop.md, packages/react/package.json, packages/react/src/components/form/flow.ts, packages/react/src/components/form/useFlowState.ts, packages/remix/package.json, pnpm-lock.yaml
[YouTrack issue](https://todo.irdcorp.dev/issue/SID-1742)
This PR resolves the issue of flow cancellation when the polling doesn't stop if you cancel the flow,
=> [SID-1742] React SDK: Send FlowCancelled event when the flow is cancelled

.changeset/quiet-suits-study.md, packages/react-primitives/src/components/text/index.tsx, packages/react-primitives/src/components/text/text.css.ts
[YouTrack issue](https://todo.irdcorp.dev/issue/SID-1773)
Same as https://github.com/slashid/javascript/pull/277 but using CSS only
=> [SID-1773] React: use css to support line breaks

.changeset/green-mugs-flash.md, packages/react-primitives/package.json, packages/react-primitives/scripts/test-setup.js, packages/react-primitives/src/components/text/index.tsx, packages/react-primitives/src/components/text/text.test.tsx, packages/react/src/components/dynamic-flow/index.tsx, packages/react/src/components/form/authenticating/authenticating.components.tsx, packages/react/src/components/form/authenticating/authenticating.test.tsx, packages/react/src/components/form/authenticating/index.tsx, packages/react/src/components/form/authenticating/otp.tsx, packages/react/src/components/form/authenticating/password.tsx, packages/react/src/components/form/authenticating/totp.tsx, packages/react/src/components/form/form-customisation.test.tsx, packages/react/src/components/form/form.tsx, packages/react/src/components/form/states.tsx, packages/react/src/components/text/constants.ts, packages/react/src/dev.tsx
[YouTrack issue](https://todo.irdcorp.dev/issue/SID-1779)
Form title did not have a stable class name, so I added two of them - a generic one that is always there and a conditional one that appears based on the flow type.
There were no tests for the `Text` component and the interpolation feature so I added those too.
Form can now render a `subtitle` in the `Authenticating` state, but this appears only if you specify the required text key. This was a request from GetHarley, as it lets them customise the Authenticating state without overriding it completely.
Published beta version: `@slashid/react@1.26.0-authenticating-slot.1`
=> [SID-1779] Add class names to Form title and subtitle, fix Authenticating slot

.changeset/wicked-spies-deliver.md, packages/react/src/components/dynamic-flow/handle-form.tsx, packages/react/src/components/form/initial/controls.tsx
[YouTrack issue](https://todo.irdcorp.dev/issue/SID-1847)
When entering handle, the inputs have the following types:
- Phone number: `tel`
- Username: `text`
- Email: `text`
This PR changes email to type `email`, and explicitly sets phone number to type `tel` (though, this is the default already).
The intent is better semantics, and to allow better integration with browsers, and other tools depending on the field being correctly typed.
=> React: use type=email for email handle input

.changeset/eight-brooms-divide.md, packages/react/src/context/slash-id-context.tsx, packages/react/src/context/test-providers.tsx, packages/remix/src/slashid-provider.tsx
[YouTrack issue](https://todo.irdcorp.dev/issue/SID-1793)
Only merge if needed - sync SDK with external state stores, reinitialize the SDK when token changes externally.
=> [SID-1793] Add a private function to sync the SDK with external state (oid, token)

.changeset/short-yaks-remain.md, packages/react/package.json, packages/react/src/components/form/error/error.test.tsx, packages/react/src/components/form/error/index.tsx, packages/react/src/components/form/flow.ts, packages/react/src/domain/errors.ts, packages/remix/package.json, pnpm-lock.yaml
[YouTrack issue](https://todo.irdcorp.dev/issue/SID-1890)
Use the new type guards and the `SlashIDError` type from the core SDK.
=> [SID-1890] React SDK: Use the core SDK error handling beta

.changeset/hot-rules-mix.md, packages/react/src/components/form/form.test.tsx, packages/react/src/components/form/form.tsx, packages/react/src/components/form/initial/controls.tsx, packages/react/src/components/form/internal-context.ts, packages/react/src/context/config-context.tsx, packages/react/src/domain/types.ts, packages/react/src/hooks/use-last-factor.ts
[YouTrack issue](https://todo.irdcorp.dev/issue/SID-1935)
We already have a functionality to store last used handle. This PR adds another configuration property to store last used authentication factor and pre-select it in the dropdown (works for non-oidc factors only).
=> [SID-1935] Pre-select last used auth method

.changeset/nasty-bats-warn.md, packages/react/src/components/form/authenticating/messages.ts, packages/react/src/components/form/authenticating/otp.tsx
[YouTrack issue](https://todo.irdcorp.dev/issue/SID-1961)
Fix the issue where the retry message was displayed instead of the regular submitting message when you submit the OTP code after resending the code at least once.
=> [SID-1961] Fix the incorrect submit state after resending an OTP code

.changeset/healthy-kiwis-yell.md, packages/react/src/components/form/authenticating/otp.tsx
[YouTrack issue](https://todo.irdcorp.dev/issue/SID-1998)
Render the `resend` button immediately when entering the Authenticating state in the OTP flow.
=> [SID-1998] Render the Resend button in the correct state of the OTP flow

.changeset/gold-zebras-stare.md, packages/demo-form/src/components/User/index.tsx, packages/demo-form/src/pages/CompositeFormPage/composite-form-page.tsx, packages/react/package.json, packages/react/src/components/form/authenticating/authenticating.test.tsx, packages/react/src/components/form/authenticating/authenticating.types.ts, packages/react/src/components/form/authenticating/index.tsx, packages/react/src/components/form/authenticating/otp.tsx, packages/react/src/components/form/authenticating/password.tsx, packages/react/src/components/form/authenticating/totp.tsx, packages/react/src/components/form/error/error.test.tsx, packages/react/src/components/form/event-buffer.test.ts, packages/react/src/components/form/event-buffer.ts, packages/react/src/components/form/flow.ts, packages/react/src/components/form/form.test.tsx, packages/react/src/context/slash-id-context.tsx, packages/react/src/context/test-providers.tsx, packages/react/src/dev.tsx, packages/remix/package.json, packages/remix/src/slashid-provider.tsx, pnpm-lock.yaml
[YouTrack issue](https://todo.irdcorp.dev/issue/SID-2019)
It is possible to miss events published by the core SDK due to race conditions. Having an event buffer makes this less likely to happen as it will replay the events that happened prior the subscription.
With this PR the React SDK will be able to buffer events that were published before any listeners had any chance to process these events. It uses that mechanism to listen to the new event type that establishes the authentication context upon processing the related challenge.
This is a big change, since previously the authentication context was established by the values submitted in the initial step. Now that this can be changed using a sync webhook,  we need to wait for the core SDK to tell us what the auth context it.
=> [SID-2019] Process the authn context update event

.changeset/cyan-bears-shout.md, packages/react-primitives/src/components/dropdown/dropdown.css.ts, packages/react-primitives/src/components/tabs/tabs.css.ts, packages/react/src/dev.css
=> React SDK: Add line-height for select label

.changeset/curvy-owls-repair.md, packages/react/src/components/form/event-buffer.test.ts, packages/react/src/components/form/event-buffer.ts
[YouTrack issue](https://todo.irdcorp.dev/issue/SID-2056)
When the last subscriber of an event type would unsubscribe, the event buffer was supposed to buffer any future instances of this event type and replay them to the first subscriber. Due to a bad state check this wouldn't happen if you had already subscribed to this event type, unsubscribed and then subscribed again.
This issue is now fixed and a unit test was added that confirms this.
=> [SID-2056] React SDK: back button blocked

.changeset/wet-hotels-bow.md, packages/react/src/components/form/authenticating/validation.test.ts, packages/react/src/components/form/authenticating/validation.ts
The BE normalises the email address value before validating it. We use the same regex, but the FE did not perform normalization. Now we lowercase all the characters before validating, removing false positives.
=> [Bugfix] Email addresses should be normalised before validation

.changeset/nine-rats-judge.md, .github/workflows/bundle-size.yml, .github/workflows/ci.yml, .github/workflows/release.yml, packages/react/vite.config.ts
Previous PR had the `@slashid/slash` module being included in the bundle while it is supposed to be external.
=> Ensure that peer deps are externalized

.changeset/tricky-gifts-compare.md, packages/react/src/context/slash-id-context.tsx, packages/react/src/domain/org.ts, packages/react/src/tests/anonymous-users.test.tsx, packages/react/src/tests/token-storage.test.tsx
When the org switching flow involves a redirect (in case of SSO via OIDC/SAML), the SDK would not finish the flow properly as after loading the page again it loses any in-memory context.
Specifically, we observed this sequence of events in the SlashID Console:
- a user logs in to the root dashboard org (local storage has the token stored under root oid)
- then they switch to the target org
- assuming SAML is configured properly, they get redirected to the IdPs login page
- after successful auth they are redirected back to the Console
Then the SDK does the following:
- there are challenges in the URL so it resolves them, obtaining a new token for the target org
- since the OID hasn't changed, the new token is stored under the initial OID, which is the root org ID
- then the Console …
=> [Bugfix] Ensure the org switch flow works with redirect

.changeset/lovely-pandas-film.md, packages/react/package.json, packages/react/src/components/form/authenticating/otp.tsx, packages/remix/package.json, pnpm-lock.yaml
=> React SDK: Fix OTP error handling

packages/react/src/components/onboarding/onboarding-form.component.tsx, packages/react/src/components/onboarding/onboarding.component.tsx, packages/react/src/context/slash-id-context.test.tsx, packages/react/src/context/slash-id-context.tsx
When initialising the SDK we try to hydrate the user token from several sources. Some of this attempts may fail, for example when parsing the URL for challenges we might encounter an incorrectly formatted challenge pack or an expired challenge ID.
The SDK will resume its lifecycle as if nothing happened, but it is useful for client apps to know if something went wrong so this PR exposes the `onInitError` callback for that purpose. The behaviour remains unchanged.
=> Add the onInitError callback
